sudo: false

addons:
    apt_packages:
        - lib32stdc++6  # needed for spcomp

before_script:
    # install smbuilder
    - git clone https://github.com/splewis/sm-builder
    - cd sm-builder
    - pip install --user -r requirements.txt
    - python setup.py install --prefix=~/.local
    - cd ..

    # install the sourcemod compiler
    - wget http://www.gsptalk.com/mirror/sourcemod/sourcemod-1.7.2-linux.tar.gz
    - tar -xzf sourcemod-1.7.2-linux.tar.gz
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - PATH+=":$PWD"

    # install smlib
    - cd include
    - git clone https://github.com/bcserv/smlib
    - cp -r smlib/scripting/include/* .
    - cd ../../../..

script:
    - smbuilder --flags="-E"

notifications:
    email: false
